version: '3.5'

services:
  buyer-service:
    build:
      context: ./../buyer-service
      dockerfile: ./../buyer-service/buyer-service.dockerfile
    image: buyer-service-img
    container_name: ${BUYER_SERVICE_NAME}
    restart: always
    ports:
      - "${BUYER_SERVICE_PORT}:${BUYER_SERVICE_PORT}" # Maps the buyer-service port from .env
    environment:
      - BUYER_SERVICE_PORT=${BUYER_SERVICE_PORT}
      - BUYER_SERVICE_NAME=${BUYER_SERVICE_NAME}
    env_file:
      - .env # Ensure the environment variables are read from this file
    deploy:
      mode: replicated
      replicas: 1

  seller-service:
    build:
      context: ./../seller-service
      dockerfile: ./../seller-service/seller-service.dockerfile
    image: seller-service-img
    container_name: ${SELLER_SERVICE_NAME}
    restart: always
    ports:
      - "${SELLER_SERVICE_PORT}:${SELLER_SERVICE_PORT}" # Maps the seller-service port from .env
    environment:
      - SELLER_SERVICE_PORT=${SELLER_SERVICE_PORT}
      - SELLER_SERVICE_NAME=${SELLER_SERVICE_NAME}
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 1

  authentication-service:
    build:
      context: ./../authentication-service
      dockerfile: ./../authentication-service/authentication-service.dockerfile
    image: authentication-service-img
    container_name: ${AUTHENTICATION_SERVICE_NAME}
    restart: always
    ports:
      - "${AUTHENTICATION_SERVICE_PORT}:${AUTHENTICATION_SERVICE_PORT}" # Maps the authentication-service port from .env
    environment:
      - AUTHENTICATION_SERVICE_PORT=${AUTHENTICATION_SERVICE_PORT}
      - AUTHENTICATION_SERVICE_NAME=${AUTHENTICATION_SERVICE_NAME}
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 1

  postgres:
    image: postgres:16.6
    container_name: postgres
    ports:
      - "${POSTGRES_DB_PORT}:5432" # Map the PostgreSQL default port
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    volumes:
      - ./db-data/postgres:/var/lib/postgresql/data
    deploy:
      mode: replicated
      replicas: 1