version: '3.9'

services:
  # User Service
  user-service:
    build:
      context: ./../user-service
      dockerfile: ./../user-service/user-service.dockerfile
    image: ${USER_SERVICE_IMAGE_NAME}
    container_name: ${USER_SERVICE_CONTAINER_NAME}
    restart: always
    depends_on:
      user-db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - USER_SERVICE_PORT=${USER_SERVICE_PORT}
      - USER_SERVICE_NAME=${USER_SERVICE_NAME}
      - USER_SERVICE_JWT_SECRET=${USER_SERVICE_JWT_SECRET}  # Adding JWT Secret here
    networks:
      - app-network

  # User Database
  user-db:
    image: postgres:15
    container_name: ${USER_POSTGRES_DB_CONTAINER_NAME}
    restart: always
    environment:
      POSTGRES_USER: ${USER_POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${USER_POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${USER_POSTGRES_DB_NAME}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${USER_POSTGRES_DB_USER}", "-d", "${USER_POSTGRES_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - user_db_data:/var/lib/postgresql/data
    networks:
      - app-network

  # Mail Service
  mail-service:
    build:
      context: ./../mail-service
      dockerfile: ./../mail-service/mail-service.dockerfile
    image: ${MAIL_SERVICE_IMAGE_NAME}
    container_name: ${MAIL_SERVICE_CONTAINER_NAME}
    restart: always
    depends_on:
      user-db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - MAIL_SERVICE_PORT=${MAIL_SERVICE_PORT}
    networks:
      - app-network

  # Mail Database
  mail-db:
    image: postgres:15
    container_name: ${MAIL_POSTGRES_DB_CONTAINER_NAME}
    restart: always
    environment:
      POSTGRES_USER: ${MAIL_POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${MAIL_POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${MAIL_POSTGRES_DB_NAME}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${MAIL_POSTGRES_DB_USER}", "-d", "${MAIL_POSTGRES_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mail_db_data:/var/lib/postgresql/data
    networks:
      - app-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./../frontend/build:/usr/share/nginx/html
    depends_on:
      - user-service
      - mail-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  user_db_data:
  mail_db_data:
