version: '3.5'

services:
  buyer-service:
    build:
      context: ./../buyer-service
      dockerfile: ./../buyer-service/buyer-service.dockerfile
    restart: always
    container_name: ${BUYER_SERVICE_NAME}
    image: buyer-service-img
    ports:
      - "${BUYER_SERVICE_PORT}:${BUYER_SERVICE_PORT}"  # Maps the buyer-service port from .env
    environment:
      - BUYER_SERVICE_PORT=${BUYER_SERVICE_PORT}
      - BUYER_SERVICE_NAME=${BUYER_SERVICE_NAME}
    env_file:
      - .env   # Ensure the environment variables are read from this file
    deploy:
      mode: replicated
      replicas: 1

  seller-service:
    build:
      context: ./../seller-service
      dockerfile: ./../seller-service/seller-service.dockerfile
    restart: always
    image: seller-service-img
    container_name: ${SELLER_SERVICE_NAME}
    ports:
      - "${SELLER_SERVICE_PORT}:${SELLER_SERVICE_PORT}"  # Maps the seller-service port from .env
    environment:
      - SELLER_SERVICE_PORT=${SELLER_SERVICE_PORT}
      - SELLER_SERVICE_NAME=${SELLER_SERVICE_NAME}  
    env_file:
      - .env   # Ensure the environment variables are read from this file
    deploy:
      mode: replicated
      replicas: 1
