global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8080']

  - job_name: 'mail-service'
    static_configs:
      - targets: ['mail-service:8081']
